package com.devshaks.personal_finance.kafka;

public enum ServiceNames {
    USER_SERVICE,
    TRANSACTION_SERVICE,
    BUDGET_SERVICE,
    SAVINGS_SERVICE,
    REPORTING_SERVICE,
    NOTIFICATION_SERVICE,
    INVESTMENT_SERVICE,
    CURRENCY_EXCHANGE_SERVICE,
    LOANS_SERVICE
}
