spring:
    profiles:
        active: dev
    config:
        import: optional:configserver:http://localhost:8888
            # - optional:configserver:http://configuration-service:8888
    application:
        name: user-service
