package com.devshaks.personal_finance.kafka.user;

public enum UserEvents {
    ADMIN_REGISTERED,
    ADMIN_DELETED,
    ADMIN_ROLE_CHANGED,
    USER_REACTIVATED,
    USER_DEACTIVATED,

    USER_REGISTERED,
    USER_REGISTRATION_FAILED,
    USER_DELETED,
    USER_PROFILE_UPDATED,
    USER_PROFILE_UPDATE_FAILED,
    USER_ROLE_CHANGED,

    USER_PASSWORD_RESET_SUCCESS,
    USER_PASSWORD_RESET_FAILED,
    USER_ACCOUNT_LOCKED,
    USER_ACCOUNT_UNLOCKED,
}
