global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb-ms:5432']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-ms:9092']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak-ms:9098']

  - job_name: 'user-service'
    static_configs:
      - targets: ['localhost:8090']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['localhost:8050']

  - job_name: 'audit-service'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'apiateway-service'
    static_configs:
      - targets: ['localhost:8222']

  - job_name: 'discovery-service'
    static_configs:
      - targets: ['localhost:8761']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
