package com.devshaks.personal_finance.kafka.notifications;

public enum NotificationEvents {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILURE,
    LOW_BALANCE_ALERT,
    BUDGET_THRESHOLD_REACHED,
    SAVINGS_GOAL_ACHIEVED,
    SAVINGS_GOAL_PROGRESS,
    INVESTMENT_UPDATE,
    PAYMENT_REMINDER,
    ACCOUNT_ACTIVITY,
    PROFILE_UPDATE_CONFIRMATION,
    SYSTEM_ALERT,
    PROMOTIONAL_OFFER,
    NEW_FEATURE_ANNOUNCEMENT,
    SECURITY_ALERT,
    CURRENCY_EXCHANGE_RATE,
    LOAN_APPLICATION_STATUS,
    AUDIT_LOG_UPDATE,
    CUSTOM_MESSAGE
}
