spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: "http://localhost:9098/realms/personal-finance"
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                - id: user-service
                  uri: lb:http://USER-SERVICE
                  predicates:
                      - Path=/api/v1/users/**


#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka/ # Use Docker container name
#instance:
#hostname: apigateway-service
#preferIpAddress: false # Use hostname for Eureka registration

server:
    port: 8222
