spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true

#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka/ # Use Docker container name
#instance:
#hostname: apigateway-service
#preferIpAddress: false # Use hostname for Eureka registration

server:
    port: 8222
