spring:
    data:
        mongodb:
           # username: root
            #password: root
            host: localhost
            port: 27017
            database: auditdb
            #authentication-database: admin

    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: auditGroup
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: "*"
                spring.json.type.mapping: com.devshaks.personal_finance.kafka.UserEventDTO:com.devshaks.personal_finance.kafka.UserEventDTO

logging:
    level:
        org.springframework.kafka: DEBUG
        org.springframework.data.mongodb: DEBUG




server:
    port: 8080