spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: notificationsdb

application:
    config:
        SES_ACCESS_KEY: ${SES_ACCESS_KEY}
        SES_SECRET_ACCESS_KEY: ${SES_SECRET_ACCESS_KEY}

server:
    port: 8040
