spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: notificationsdb

application:
    config:
        SES_ACCESS_KEY: ${SES_ACCESS_KEY}
        SES_SECRET_ACCESS_KEY: ${SES_SECRET_ACCESS_KEY}
        TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
        TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
        TWILIO_PHONE_NUM: ${TWILIO_PHONE_NUM}

server:
    port: 8040
