spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/userdb
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    kafka:
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: com.devshaks.personal_finance.kafka.UserEventDTO:com.devshaks.personal_finance.kafka.UserEventDTO

    security:
        adminCode: ${SUPER_ADMIN_CODE}

logging:
    level:
        org.springframework.kafka: DEBUG


server:
    port: 8090
#eureka:
#   client:
#        serviceUrl:
#            defaultZone: http://discovery-service:8761/eureka/ # Use Docker container name
#    instance:
#        hostname: user-service
#        preferIpAddress: false # Use hostname for Eureka registration
