spring:
    datasource:
        url: jdbc:postgresql://timescaledb:5432/userdb
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

server:
    port: 8090
#eureka:
#   client:
#        serviceUrl:
#            defaultZone: http://discovery-service:8761/eureka/ # Use Docker container name
#    instance:
#        hostname: user-service
#        preferIpAddress: false # Use hostname for Eureka registration
