spring:
  datasource:
    url: jdbc:postgresql://timescaledb:5432/userdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    database: timescaledb
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #kafka:

server:
  port: 8090
