spring:
    config:
        import:
            #optional:configserver:http://configuration-service:8888
            - optional:configserver:http://localhost:8888
    application:
        name: apigateway-service
