package com.devshaks.personal_finance.kafka;

public enum EventType {
    ADMIN_REGISTERED,
    ADMIN_DELETED,
    ADMIN_ROLE_CHANGED,

    USER_REGISTERED,
    USER_DELETED,
    USER_PROFILE_UPDATED,
    USER_ROLE_CHANGED,

    USER_LOGGED_IN,
    USER_LOGIN_FAILED,
    USER_LOGGED_OUT,

    USER_REGISTRATION_FAILED,

    USER_PASSWORD_CHANGED,
    USER_PASSWORD_RESET_REQUESTED,
    USER_PASSWORD_RESET_SUCCESS,
    USER_PASSWORD_RESET_FAILED,
    USER_ACCOUNT_LOCKED,
    USER_ACCOUNT_UNLOCKED,

    USER_PROFILE_UPDATE_FAILED

    // Transaction Events

    // Budget Events
}

